### ISSUE TITLE
请求支持simple-obfs

### ISSUE THREAD

**Issue by ghost** [rixCloud-Inc/Feature-Request#2]
# rixCloud Feature Request

请不要将任何有关您个人信息的内容提交在这里，如有相关内容，您可以提交一个工单，在工单中提供相关信息，然后在这里提供您的 Ticket ID。

图片可以使用 [SM.MS](https://sm.ms) 图床。

Please do not submit any private or your personal information here. If you have any personal relevant content, you should submit a ticket at rixCloud management portal first, and then tell us your Ticket ID here.

You can use [SM.MS](https://sm.ms) image hosting if you need to show us any relevant photo.

**您的功能请求是否与某个故障有关？ 请描述一下。**
**Is your feature request related to a problem? Please describe.**

校园网的QoS比较严重，未加混淆的ss速度受到一定影响

---

**这个请求与什么 rixCloud 服务相关？请在对应项目的 `[ ]` 中以 `x` 填充**
**Which rixCloud service/product is this request related with? Please fill in the `[  ]`  with `x` symbol**

示例：使用 `x` 填充选择框
ex. Fill in the box with `x`
- [x] rixCloud Feature Request Example - rixCloud 功能请求示例

---

- [ ] rixCloud.com (also known as rixCloud Homepage - 也可称为 rixCloud 首页)
- [ ] rixCloud Management Portal - rixCloud 管理门户
- [ ] rixCloud Subscription Dashbaord - rixCloud 订阅管理面板
- [ ] rixCloud License Dashboard - rixCloud 授权管理门户
- [ ] rixCloud API
- [ ] rixCloud Status Portal - rixCloud 状态面板
- [ ] rixCloud Email Delivery Service - rixCloud 邮件推送服务
- [ ] rixCloud Knowledge Base - rixCloud 知识库
- [x] rixCloud Endpoint - rixCloud 接入点

---

**描述您想要的解决方案**
**Describe the solution you'd like**

rixCloud的接入点支持simple-obfs

---

**描述您考虑过的替代方案**
**Describe alternatives you've considered**

使用SSR，但在部分安卓机型上发生严重的断流问题

---

**附加信息**
**Additional context**

**Comment by ZeroClover** [comment]
此功能已经在 rixCloud Endpoint 中支持并预计在 rixCloud API v2 中开放使用。

**Comment by ZeroClover** [comment]
现已经支持此功能
